# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tcoapp', '0002_auto_20161018_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture_img', models.ImageField(blank=True, null=True, upload_to='architectures')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureArchitecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_img', models.ImageField(blank=True, null=True, upload_to='architectures/features/')),
                ('architecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcoapp.Architecture')),
            ],
        ),
    ]
