# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcoapp', '0003_architecture_featurearchitecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='architecture_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
