# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcoapp', '0005_auto_20161019_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='featurearchitecture',
            name='architecture_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='featurearchitecture',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='featurearchitecture',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
